import { app, BrowserWindow, session, ipcMain, webContents } from 'electron';
import dotenv from 'dotenv';
import { chromium } from 'playwright';
import moment from 'moment-timezone';
import * as cheerio from 'cheerio';
import { ImparcialDb } from './db';
import ImparcialApi from './ImparcialApi';
import { EventScraperData, LawScraperData, ScrapingJobState } from './app/lib/models';

import https from 'node:https';
import fs from "node:fs";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

dotenv.config({ path: ".env"});

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

if (app.isPackaged) {
  // Path when the app is packaged
  // Note: Adjust the relative path based on where you placed the file in extraResources
} else {
  // Path when running in development
  process.env.PA_SUTRA_PEM_PATH = "/Users/marcel/Projects/Imparcial/pa_electron/src/sutra.pem";
  process.env.PA_GO_DADDY_CA_PEM_PATH = "/Users/marcel/Projects/Imparcial/pa_electron/src/go_daddy_merged_ca.pem";

}


const createWindow = (): void => {
  
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 1080,
    width: 1920,
    minHeight: 800,
    minWidth: 1200,
    frame: false,
    titleBarStyle: 'hiddenInset',
    // titleBarOverlay: { height: 50 },
    acceptFirstMouse: true,
    // titleBarOverlay: { // Optional: for more control over the overlay area
    //   color: '#2f3241',
    //   symbolColor: '#74b1be',
    //   height: 30
    // },
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
      contextIsolation: true,
      nodeIntegrationInWorker: true
    },
  });

  ipcMain.removeHandler('fetch-page');
  ipcMain.handle('fetch-page', async (event, args) => {
    const url = args[0];
    const page = await fetch(url, {
        method: 'GET',
        headers: {
            'User-Agent': "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"
        }
    });
    const html = await page.text();
    return html;
  });


  ipcMain.removeHandler('fetch-page-playwright');
  ipcMain.handle('fetch-page-playwright', async (event, args) => {
    const url = args[0];
    const browser = await chromium.launch();  // Or 'firefox' or 'webkit'.
    const page = await browser.newPage();
    await page.goto(url, {waitUntil: "load", timeout: 240000});
    const html = await page.content();
    await browser.close();
    return html;
  });

  ipcMain.removeHandler('start-scraping-job');
  ipcMain.handle('start-scraping-job', async (event, args) => {
    console.log("Called start-scraping-job");
    const db = new ImparcialDb();
    let scrapingJobId = 0;
    const scrapedDate = moment().tz("America/Puerto_Rico").format();
    const jobType = args[0] as string;
    // // save scraping job
    const addScrapingJobQuery = "INSERT INTO ScrapingJob (ObjectQty, JobStartDate, JobType, Processed, Status) VALUES (?,?,?,?,?);";
    await db.run(addScrapingJobQuery, [0, scrapedDate, jobType, false, "NOT_PROCESSED"]);
    scrapingJobId = db.getLastId();
    return {ScrapingJobId: scrapingJobId, ScrapingDate: scrapedDate};
  });

  ipcMain.removeHandler('save-scraped-stories');
  ipcMain.handle('save-scraped-stories', async (event, args) => {
    const db = new ImparcialDb();
    const stories = args[0] as any[];
    console.log(`save-scraped-stories - stories: ${stories.length}`)
    const newsScrapingState = args[1] as ScrapingJobState;
    let scrapedDate = "";
    let scrapingJobId = 0;
    console.log({newsScrapingState});
    if(newsScrapingState && newsScrapingState.ScrapingJobId > 0) {
      scrapingJobId = newsScrapingState.ScrapingJobId;
      scrapedDate = newsScrapingState.ScrapingDate;
    }
    else {
      // query last scraping job for news
      const scrapingJob = await db.get("SELECT ScrapeJobId, JobStartDate from ScrapingJob WHERE JobType = 'NEWS_SCRAPER' AND Processed = 0 AND Status = 'NOT_PROCESSED' LIMIT 1;");
      if(scrapingJob) {
        scrapingJobId = scrapingJob.ScrapeJobId;
        scrapedDate = scrapingJob.JobStartDate;
      }
      else {
        throw new Error("No scraping job news found for news scraper");
      }
    }
    const addStory = "INSERT INTO story (Title, Description, Uri, SourceTypeId, Media, ScrapedDate, Hash, ArticleText, CanSummarize) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?);"
    const insertNotification = "INSERT INTO NotificationJob (ObjectQty, Data, JobDate, JobType, Processed, Status) VALUES (?, ?, ?, ?, ?, ?);"
    const lookupStory = "SELECT count(StoryId) as count FROM Story where Hash = ?;"
    const updateScrapingJobQuery = "UPDATE ScrapingJob SET ObjectQty = ?, Processed = ?, Status = ?, JobEndDate = ? WHERE ScrapeJobId = ?;"
    // Add stories to database
    let filteredStories: any[] = [];
    // check if stories already exist
    for(let i=0; i < stories.length; i++) {
        const story = await db.get(lookupStory, [stories[i].hash]);
        if(story && story.count == 0) {
            // console.log("try to add to filtered list")
            // add story to filtered list
            const foundIndex = filteredStories.findIndex((filtered) => filtered.hash == stories[i].hash);
            // console.log({foundIndex});
            if(foundIndex == -1)
                filteredStories.push(stories[i]);
        }
    }

    console.log(`save-scraped-stories - filteredStories: ${filteredStories.length}`);

    let insertComplete = false;
    let insertAttempts = 0
    let maxInsertAttempts = 3
    while (insertAttempts < maxInsertAttempts && !insertComplete) {
        insertAttempts++;
        try {
          // add stories
          for(let ii=0; ii < filteredStories.length; ii++) {
            const _story = filteredStories[ii];
            await db.run(addStory, [_story.title, _story.description, _story.uri, _story.storyType, _story.media, _story.scrapedDate, _story.hash, _story.articleText, _story.canSummarize]);
          }

          // add notification job
          // ObjectQty, Data, JobDate, JobType, Processed, Status
          await db.run(insertNotification, [filteredStories.length, JSON.stringify(filteredStories), scrapedDate, "NEWS", false, "NOT_PROCESSED"]);
          const jobEndDate = moment().tz("America/Puerto_Rico").format();
          await db.run(updateScrapingJobQuery, [filteredStories.length, true, "PROCESSED", jobEndDate, scrapingJobId]);
          insertComplete = true;
        } catch (error) {
          console.log(`Insert attempt ${insertAttempts} exception: ${error}`);
        }
    }
    db.close();
    return insertComplete;
  });

  ipcMain.removeHandler('fetch-pages-for-laws');
  ipcMain.handle('fetch-pages-for-laws', async (event, args) => {
    let scraperData: LawScraperData = {
      Pages: [],
      ScrapingDate: moment().tz("America/Puerto_Rico").format()
    };
    const administrationId = args[0] as number;
    console.log({administrationId});
    const committiees = args[1] as number[];
    console.log({committiees})

    let pageCounter = 0;
	  let html = "";
    const browser = await chromium.launch();  // Or 'firefox' or 'webkit'.
    const page = await browser.newPage();
    for(let i=0; i < committiees.length; i++) {
      pageCounter = 1;
      while(true) {
        await page.goto(`https://sutra.oslpr.org/medidas?cuatrienio_id=${administrationId}&comision_id=${committiees[i]}&per_page=50&page=${pageCounter}`, {timeout: 240000, waitUntil: 'load'});
        html = await page.content();
        pageCounter++;
        const $ = cheerio.load(html);
        console.log(`Committee: ${committiees[i]} - ${$('ul > a').length}`);
        const hasListItems = $('ul > a').length > 0;
        if(!hasListItems) {
          console.log(`No data. Skipping committiee: ${committiees[i]}.`);
          break;
        }
        else {
          scraperData.Pages.push({
            Page: html,
            Committiee: committiees[i],
            AdministrationId: administrationId
          });
        }
      }
    }
    page.close();
    browser.close();
    return scraperData;
  });

  ipcMain.removeHandler('fetch-pages-for-recent-laws');
  ipcMain.handle('fetch-pages-for-recent-laws', async (event, args) => {
    let scraperData: LawScraperData = {
      Pages: [],
      ScrapingDate: moment().tz("America/Puerto_Rico").format()
    };
    const administrationId = args[0] as number;
    console.log({administrationId});

    let pageCounter = 1;
	  let html = "";
    const browser = await chromium.launch();  // Or 'firefox' or 'webkit'.
    const page = await browser.newPage();
    
    while(true) {
      await page.goto(`https://sutra.oslpr.org/medidas?cuatrienio_id=${administrationId}&per_page=50&page=${pageCounter}`, {timeout: 240000, waitUntil: 'load'});
      html = await page.content();
      const $ = cheerio.load(html);
      const hasListItems = $('ul > a').length > 0;
      if(!hasListItems) {
        console.log(`No data. Skipping page: ${pageCounter}.`);
        break;
      }
      else {
        scraperData.Pages.push({
          Page: html,
          Committiee: -1,
          AdministrationId: administrationId
        });
      }
      pageCounter++;
    }
    page.close();
    browser.close();
    return scraperData;

  });

  ipcMain.removeHandler('fetch-pages-for-events');
  ipcMain.handle('fetch-pages-for-events', async (event, args) => {
    const db = new ImparcialDb();
    const administrationId = args[0] as number;
    let scraperData: EventScraperData = {
      Pages: [],
      ScrapingDate: moment().tz("America/Puerto_Rico").format()
    };
    // get projects and urls from database
    const getProjectInfo = "SELECT DISTINCT l.LegislationId, l.Uri from SubscribedProject as s INNER JOIN Legislation as l ON l.LegislationId = s.LegislationIdFk;"
    const subscribedProjects = await db.all(getProjectInfo);
    const browser = await chromium.launch();  // Or 'firefox' or 'webkit'.
    const page = await browser.newPage();
    let html = "";

    if(subscribedProjects) {
      for(let i=0; i < subscribedProjects.length; i++) {
        await page.goto(subscribedProjects[i].Uri, {timeout: 24000, waitUntil: 'load'});
        html = await page.content();
        scraperData.Pages.push({
          Page: html,
          LegislationId: subscribedProjects[i].LegislationId,
          AdministrationId: administrationId
        })
      }
    }

    return scraperData;
  });

  ipcMain.removeHandler('test-download');
  ipcMain.handle('test-download', async (event, args) => {
    console.log("Starting test download....");
    const administrationId = 2025;
    const legislationId = 0;
    const url = "https://sutra.oslpr.org/medidas/154598";
    const browser = await chromium.launch();  // Or 'firefox' or 'webkit'.
    const page = await browser.newPage();
    await page.goto(url, {timeout: 24000, waitUntil: 'load'});
    const html = await page.content();
    
    const $ = cheerio.load(html);
    // divide-y divide-gray-100

    const listItems = $('ul.divide-y.divide-gray-100').find('li');
    let body = "";
    let workingBody = "";
    let eventTitle = "";
    // let paragraphs = [];
    let hash = "";
    let events: any = [];
    console.log("Starting looping through list items...");
    for(let i=0; i < listItems.length; i++) {
      eventTitle = $(listItems[i]).find('h2').text().trim();
      console.log(`Event title: ${eventTitle}`);
      if(eventTitle = "Radicado") {
        console.log("Found Radicado event");
        const paragraphs = $(listItems[i]).find('p');
        for(let ii=0; ii < paragraphs.length; ii++) {
          workingBody = $(paragraphs[ii]).text().trim();
          if(!workingBody.includes("doc") && !workingBody.includes("docx") && !workingBody.includes("pdf")) {
            body += workingBody;
            body += "\n";
          }
        }

        // hash = crypto.createHash('sha256').update(administrationId.toString() + eventTitle + body + legislationId.toString()).digest('hex');
        hash = '';

        const event: any = {
          eventTitle,
          body,
          hash
        }

        if($(listItems[i]).find('a').length > 0) {
          const uri = "https://sutra.oslpr.org" + $(listItems[i]).find('a').attr('href');
          const docType = $(listItems[i]).find('a').attr('href').split('.').at(-1);
          // download doc
          try {
            console.log(`process.env.PA_SUTRA_PEM_PATH: ${process.env.PA_SUTRA_PEM_PATH}`);
            console.log("Starting download for Radicado...");
            const win = BrowserWindow.getFocusedWindow();
            if(win) {
              console.log("win is good");
              win.webContents.downloadURL(uri);
              session.defaultSession.once('will-download', async (e, item, webContents) => {
                e.preventDefault();
                console.log('will-download called');
                let chunks: any = [];
                // {ca: process.env.PA_SUTRA_PEM_PATH}
                https.get(item.getURL(), {ca: fs.readFileSync(process.env.PA_GO_DADDY_CA_PEM_PATH),cert: fs.readFileSync(process.env.PA_SUTRA_PEM_PATH)},
                (response) => {
                  response.on('data', (chunk) => {
                    console.log("got chunk");
                    chunks.push(chunk); // Collect data chunks
                  });

                  response.on('end', () => {
                    const totalBytes = Buffer.concat(chunks); // Combine all chunks into a single Buffer
                    // Now 'totalBytes' is a Buffer containing the complete file data
                    console.log(`Downloaded ${totalBytes.length} bytes in memory.`);
                    const buffer = Buffer.from(chunks);
                    event.document = {
                      blob: buffer,
                      uri,
                      docType
                    };
                    events.push(event);
                    // You can then use this buffer as needed, e.g., save it to a specific path
                    // fs.writeFileSync('/path/to/save/file.ext', totalBytes);
                  });
                }).on('error', (error) => {
                  console.error('Download error:', error);
                });

              });
            }
          } catch (error) {
            console.log(`Error downloading project: ${error}`);
          }
        }

        break;
      }
    }

    console.log("Done!")
    for(let x=0; x < events.length; x++) {
      console.log(`Event: ${JSON.stringify(events[x])}`);
    }
  });

  ipcMain.removeHandler('save-scraped-laws');
  ipcMain.handle('save-scraped-laws', async (event, args) => {
    const db = new ImparcialDb();
    const laws: any[] = args[0];
    const administrationId = args[1] as number;
    const scrapingJobState = args[2] as ScrapingJobState;
    let scrapingJobId = -1;
    let scrapedDate = '';

    if(scrapingJobState && scrapingJobState.ScrapingJobId > 0) {
      scrapingJobId = scrapingJobState.ScrapingJobId;
      scrapedDate = scrapingJobState.ScrapingDate;
    }
    else {
      // query last scraping job for laws
      const scrapingJob = await db.get("SELECT ScrapeJobId, JobStartDate from ScrapingJob WHERE JobType = 'LAW_SCRAPER' AND Processed = 0 AND Status = 'NOT_PROCESSED' LIMIT 1;");
      if(scrapingJob) {
        scrapingJobId = scrapingJob.ScrapeJobId;
        scrapedDate = scrapingJob.JobStartDate;
      }
      else {
        throw new Error("No scraping job found for law scraper");
      }
    }

    const lookupLegislation = "SELECT value from json_each(?) WHERE value not in (SELECT Hash FROM Legislation);";
    const addLegislationQuery = "INSERT INTO Legislation(Number, FiledDate, Title, Author, CoAuthor, Uri, Committe, AdministrationId, LastEvent, ScrapedDate, Hash) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";
    // const lastInsert = "SELECT last_insert_rowid();";
    const insertEventsQuery = "INSERT OR IGNORE INTO LegislationEvent(Title, Description, Uri, Document, DocType, ScrapedDate, Hash, LegislationIdFk, CreatedDate) VALUES (?,?,?,?,?,?,?,?,?);";
    const addNotifcationQuery = "INSERT INTO NotificationJob (ObjectQty, Data, JobDate, JobType, Processed, Status) VALUES (?, ?, ?, ?, ?, ?);";
    const updateScrapingJobQuery = "UPDATE ScrapingJob SET ObjectQty = ?, Processed = ?, Status = ?, JobEndDate = ? WHERE ScrapeJobId = ?;";

    const getLegislationEvent = async (url: string, legislationId: number) => {
      const browser = await chromium.launch();  // Or 'firefox' or 'webkit'.
      const page = await browser.newPage();
      await page.goto(url, {timeout: 24000, waitUntil: 'load'});
      const html = await page.content();
      
      const $ = cheerio.load(html);
      // divide-y divide-gray-100

      const listItems = $('ul.divide-y.divide-gray-100').find('li');
      let body = "";
      let workingBody = "";
      let eventTitle = "";
      // let paragraphs = [];
      let hash = "";
      let events = [];
      for(let i=0; i < listItems.length; i++) {
        eventTitle = $(listItems[i]).find('h2').text().trim();
        if(eventTitle = "Radicado") {
          const paragraphs = $(listItems[i]).find('p');
          for(let ii=0; ii < paragraphs.length; ii++) {
            workingBody = $(paragraphs[ii]).text().trim();
            if(!workingBody.includes("doc") && !workingBody.includes("docx") && !workingBody.includes("pdf")) {
              body += workingBody;
              body += "\n";
            }
          }

          const msgBuffer = new TextEncoder().encode(administrationId.toString() + eventTitle + body + legislationId.toString());
          const hashBuffer = await crypto.subtle.digest('SHA-256', msgBuffer);
          const hashArray = Array.from(new Uint8Array(hashBuffer));
          hash = hashArray.map(b => b.toString(16).padStart(2, '0')).join('');

          // Title, Description, Uri, Document, DocType, ScrapedDate, Hash, LegislationIdFk, CreatedDate
          const event: any = {
            Title: eventTitle,
            Description: body,
            Uri: '',
            Document: undefined,
            DocType: '',
            ScrapedDate: scrapedDate,
            Hash: hash,
            LegislationIdFk: -1,
            CreatedDate: ''
          };

          if($(listItems[i]).find('a').length > 0) {
            const uri = "https://sutra.oslpr.org" + $(listItems[i]).find('a').attr('href');
            const docType = $(listItems[i]).find('a').attr('href').split('.').at(-1);
            // download doc
            try {
              const response = await fetch(uri);
              if(response.ok) {
                // Load the entire file into memory as an ArrayBuffer
                const arrayBuffer = await response.arrayBuffer();
                const buffer = Buffer.from(arrayBuffer);
                event.Document = buffer;
                event.Uri = uri;
                event.DocType = docType;
              }
            } catch (error) {
              console.log(`Error downloading project: ${error}`);
            }
          }

          events.push(event);
          break;
        }
      }
      
      return events;
    }


    // get hashes for lookup
    const hashes = laws.map((law) => law.Hash);
    // console.log({hashes});
    const newLegislationHashes = await db.all(lookupLegislation, [JSON.stringify(hashes)]);
    // console.log({newLegislationHashes});
    let newLegislation: any[] = [];

    if(newLegislationHashes) {
      for(let i=0; i < newLegislationHashes.length; i++) {
        for (let j=0; j < laws.length; j++) {
          if(newLegislationHashes[i].value == laws[j].Hash) {
            // law is new, add
            newLegislation.push(laws[j]);
            break;
          }
        }
      }
    }

    let legislationId = -1;
    let currentLegislation = null;

    try {

      for(let ii=0; ii < newLegislation.length; ii++) {
        // insert legislation
        currentLegislation = newLegislation[ii];
        await db.run(addLegislationQuery, [newLegislation[ii].Number, newLegislation[ii].FiledDate, newLegislation[ii].Title, newLegislation[ii].Author,
          newLegislation[ii].CoAuthor, newLegislation[ii].Uri, newLegislation[ii].Committe, newLegislation[ii].AdministrationId, newLegislation[ii].LastEvent,
          newLegislation[ii].ScrapedDate, newLegislation[ii].Hash]);
        // get lastId
        legislationId = db.getLastId();
        newLegislation[ii].LegislationId = legislationId;
        
        // get Radicado event
        
        // if(legislationId > 0) {
        //   events = await getLegislationEvent(newLegislation[ii].Uri, legislationId);
        //   // insert events
        //   for(let iii=0; iii < events.length; iii++) {
        //     lastEventObj = events[iii];
        //     // LegislationEvent(Title, Description, Uri, Document, DocType, ScrapedDate, Hash, LegislationIdFk, CreatedDate
        //     await db.run(insertEventsQuery, [events[iii].Title, events[iii].Description, events[iii].Uri, events[iii].Document, events[iii].DocType, scrapedDate, events[iii].Hash, legislationId, moment().tz("America/Puerto_Rico").format()]);
        //   }
        // }
      }

      if(newLegislation.length > 0) {
        const notificationData = JSON.stringify(newLegislation);
        // ObjectQty, Data, JobDate, JobType, Processed, Status
        await db.run(addNotifcationQuery, [newLegislation.length, notificationData, moment().tz("America/Puerto_Rico").format(), "LEGISLATION", false, "NOT_PROCESSED"]);
      }
      
      await db.run(updateScrapingJobQuery, [newLegislation.length, true, "PROCESSED", moment().tz("America/Puerto_Rico").format(), scrapingJobId]);

      return true;

    } catch (error) {
      console.log(`Error saving laws: ${error}`);
      console.log(`Last attempted law insert: ${JSON.stringify(currentLegislation)}`);
      return false;
    } finally {
      db.close();
    }
    
  });
  
  ipcMain.removeHandler('save-scraped-recent-laws');
  ipcMain.handle('save-scraped-recent-laws', async (event, args) => {
    const db = new ImparcialDb();
    const laws: any[] = args[0];
    const scrapingJobState = args[1] as ScrapingJobState;
    let scrapingJobId = -1;
    let scrapedDate = '';

    if(scrapingJobState && scrapingJobState.ScrapingJobId > 0) {
      scrapingJobId = scrapingJobState.ScrapingJobId;
      scrapedDate = scrapingJobState.ScrapingDate;
    }
    else {
      // query last scraping job for recent laws
      const scrapingJob = await db.get("SELECT ScrapeJobId, JobStartDate from ScrapingJob WHERE JobType = 'RECENT_LAW_SCRAPER' AND Processed = 0 AND Status = 'NOT_PROCESSED' LIMIT 1;");
      if(scrapingJob) {
        scrapingJobId = scrapingJob.ScrapeJobId;
        scrapedDate = scrapingJob.JobStartDate;
      }
      else {
        throw new Error("No scraping job found for recent law scraper");
      }
    }

    const lookupExistingProjects = "SELECT value from json_each(?) WHERE value not in (SELECT Hash FROM RecentlyFiledLegislation) AND value not in (SELECT Hash FROM Legislation);"
    const insertRecentProject = "INSERT INTO RecentlyFiledLegislation(Number, FiledDate, Title, Author, CoAuthor, Uri, AdministrationId, LastEvent, ScrapedDate, Hash, Document, DocDesc, DocUri, DocType, EventDescription) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);"
    const addNotifcationQuery = "INSERT INTO NotificationJob (ObjectQty, Data, JobDate, JobType, Processed, Status) VALUES (?, ?, ?, ?, ?, ?);"
    const updateScrapingJobQuery = "UPDATE ScrapingJob SET ObjectQty = ?, Processed = ?, Status = ?, JobEndDate = ? WHERE ScrapeJobId = ?;"

    // get hashes for lookup
    const hashes = laws.map((law) => law.Hash);
    // hashes.forEach((e) => console.log({e}));
    // console.log({hashes});
    const newLegislationHashes = await db.all(lookupExistingProjects, [JSON.stringify(hashes)]);
    // console.log({newLegislationHashes});
    let newLegislation: any[] = [];

    if(newLegislationHashes) {
      for(let i=0; i < newLegislationHashes.length; i++) {
        for (let j=0; j < laws.length; j++) {
          if(newLegislationHashes[i].value == laws[j].Hash) {
            // law is new, add
            newLegislation.push(laws[j]);
            break;
          }
        }
      }
    }

    // console.log(`newLegislation length: ${newLegislation.length}`);

    let currentLegislation = null;
    try {
      
      for(let ii=0; ii < newLegislation.length; ii++) {
        // insert legislation
        currentLegislation = newLegislation[ii];
        // Number, FiledDate, Title, Author, CoAuthor, Uri, AdministrationId, LastEvent, ScrapedDate, Hash, Document, DocDesc, DocUri, DocType, EventDescription
        await db.run(insertRecentProject, [newLegislation[ii].Number, newLegislation[ii].FiledDate, newLegislation[ii].Title, newLegislation[ii].Author,
          newLegislation[ii].CoAuthor, newLegislation[ii].Uri, newLegislation[ii].AdministrationId, newLegislation[ii].LastEvent,
          newLegislation[ii].ScrapedDate, newLegislation[ii].Hash, newLegislation[ii].Document, newLegislation[ii].DocDesc, newLegislation[ii].DocUri,
          newLegislation[ii].DocType, newLegislation[ii].EventDescription]);

        newLegislation[ii].LegislationId = db.getLastId();
      }

      if(newLegislation.length > 0) {
        const notificationData = JSON.stringify(newLegislation);
        // ObjectQty, Data, JobDate, JobType, Processed, Status
        await db.run(addNotifcationQuery, [newLegislation.length, notificationData, moment().tz("America/Puerto_Rico").format(), "LEGISLATION", false, "NOT_PROCESSED"]);
      }

      await db.run(updateScrapingJobQuery, [newLegislation.length, true, "PROCESSED", moment().tz("America/Puerto_Rico").format(), scrapingJobId]);

      return true;

    } catch (error) {
      console.log(`Error saving laws: ${error}`);
      console.log(`Last attempted law insert: ${JSON.stringify(currentLegislation)}`);
      return false;
    } finally {
      db.close();
    }

  });


  ipcMain.removeHandler('save-scraped-events');
  ipcMain.handle('save-scraped-events', async (event, args) => {
    const db = new ImparcialDb();
    const events: any[] = args[0];
    const scrapingJobState = args[1] as ScrapingJobState;
    let scrapingJobId = -1;
    let scrapedDate = '';

    if(scrapingJobState && scrapingJobState.ScrapingJobId > 0) {
      scrapingJobId = scrapingJobState.ScrapingJobId;
      scrapedDate = scrapingJobState.ScrapingDate;
    }
    else {
      // query last scraping job for events
      const scrapingJob = await db.get("SELECT ScrapeJobId, JobStartDate from ScrapingJob WHERE JobType = 'EVENT_SCRAPER' AND Processed = 0 AND Status = 'NOT_PROCESSED' LIMIT 1;");
      if(scrapingJob) {
        scrapingJobId = scrapingJob.ScrapeJobId;
        scrapedDate = scrapingJob.JobStartDate;
      }
      else {
        throw new Error("No scraping job found for event scraper");
      }
    }

    const insertEventsQuery = "INSERT OR IGNORE INTO LegislationEvent(Title, Description, Uri, Document, DocType, ScrapedDate, Hash, LegislationIdFk, CreatedDate) VALUES (?,?,?,?,?,?,?,?,?);";
    const addNotifcationQuery = "INSERT INTO NotificationJob (ObjectQty, Data, JobDate, JobType, Processed, Status) VALUES (?, ?, ?, ?, ?, ?);";
    const updateScrapingJobQuery = "UPDATE ScrapingJob SET ObjectQty = ?, Processed = ?, Status = ?, JobEndDate = ? WHERE ScrapeJobId = ?;";

    let affectedProjects = [];

    try {
      
      for(let i=0; i < events.length; i++) {
        let doc = null;
        let docType = null;
        let uri = null;

        if(events[i]?.Document) {
          uri = events[i].Document.Uri;
          docType = events[i].Document.DocType;
          const eventFileResult = await ImparcialApi.getEventFile(uri);
          if(!eventFileResult.Error) {
            if(eventFileResult.Data) {
              doc = eventFileResult.Data;
            }
          }
        }

        await db.run(insertEventsQuery, [events[i].Title, events[i].Description, uri, doc, docType, events[i].ScrapedDate, events[i].Hash, events[i].LegislationIdFk, events[i].CreatedDate]);
        let result = await db.get("select changes() as Changes;");
        if(result.Changes > 0) {
          affectedProjects.push(events[i].LegislationIdFk);
        }
      }

      // add notification record
      if(affectedProjects.length > 0) {
        await db.run(addNotifcationQuery, [affectedProjects.length, JSON.stringify(affectedProjects), moment().tz("America/Puerto_Rico").format(), "EVENTS", 0, "NOT_PROCESSED"]);
      }

      // finish out scraping job record
      await db.run(updateScrapingJobQuery, [affectedProjects.length, true, "PROCESSED", moment().tz("America/Puerto_Rico").format(), scrapingJobId]);

      return true;

    } catch (error) {
      console.log(`Error saving events: ${error}`);
      return false;
    } finally {
      db.close();
    }

  });
 // Imparcial API

  ipcMain.removeHandler('get-stories');
  ipcMain.handle('get-stories', async (event, args) => {
    const page = args[0];
    const limit = args[1];
    const source = args[2];
    const result = await ImparcialApi.getStories(page, limit, source);
    return result;
  });

  ipcMain.removeHandler('get-story');
  ipcMain.handle('get-story', async (event, args) => {
    const hash = args[0];
    const result = await ImparcialApi.getStory(hash);
    return result;
  });

  ipcMain.removeHandler('get-legislations');
  ipcMain.handle('get-legislations', async (event, args) => {
    const page = args[0];
    const limit = args[1];
    const filter = args[2];
    const result = await ImparcialApi.getLegislations(page, limit, filter);
    return result;
  });

  ipcMain.removeHandler('get-legislation-by-hash');
  ipcMain.handle('get-legislation-by-hash', async (event, args) => {
    const hash = args[0];
    const result = await ImparcialApi.getLegislationByHash(hash);
    return result;
  });

  ipcMain.removeHandler('get-legislation-by-id');
  ipcMain.handle('get-legislation-by-id', async (event, args) => {
    const id = args[0];
    const result = await ImparcialApi.getLegislationById(id);
    return result;
  });

  ipcMain.removeHandler('get-my-projects');
  ipcMain.handle('get-my-projects', async (event, args) => {
    const page = args[0];
    const limit = args[1];
    const category = args[2];
    const result = await ImparcialApi.getMyProjects(page, limit, category);
    return result;
  });

  ipcMain.removeHandler('update-subscribed-project-tags');
  ipcMain.handle('update-subscribed-project-tags', async (event, args) => {
    const legislationId = args[0];
    const tags = args[1];
    const result = await ImparcialApi.updateSubscribedProjectTags(legislationId, tags);
    return result;
  });

  ipcMain.removeHandler('get-recent-legislations');
  ipcMain.handle('get-recent-legislations', async (event, args) => {
    const page = args[0];
    const limit = args[1];
    const filter = args[2];
    const result = await ImparcialApi.getRecentLegislations(page, limit, filter);
    return result;
  });

  ipcMain.removeHandler('search-legislation');
  ipcMain.handle('search-legislation', async (event, args) => {
    const searchText = args[0];
    const page = args[1];
    const limit = args[2];
    const result = await ImparcialApi.searchLegislation(searchText, page, limit);
    return result;
  });

  ipcMain.removeHandler('summarize-article');
  ipcMain.handle('summarize-article', async (event, args) => {
    const storyId = args[0];
    const result = await ImparcialApi.summarizeArticle(storyId);
    return result;
  });

  ipcMain.removeHandler('summarize-legislation-doc');
  ipcMain.handle('summarize-legislation-doc', async (event, args) => {
    const docId = args[0];
    const result = await ImparcialApi.summarizeLegislationDoc(docId);
    return result;
  });

  ipcMain.removeHandler('summarize-recent-legislation-doc');
  ipcMain.handle('summarize-recent-legislation-doc', async (event, args) => {
    const legislationId = args[0];
    const result = await ImparcialApi.summarizeRecentLegislationDoc(legislationId);
    return result;
  });

  ipcMain.removeHandler('get-config');
  ipcMain.handle('get-config', async (event, args) => {
    const result = await ImparcialApi.getConfig();
    return result;
  });

  ipcMain.removeHandler('update-committee-config');
  ipcMain.handle('update-committee-config', async (event, args) => {
    const committees = args[0];
    const result = await ImparcialApi.updateCommitteeConfig(committees);
    return result;
  });

  ipcMain.removeHandler('update-news-config');
  ipcMain.handle('update-news-config', async (event, args) => {
    const news = args[0];
    const result = await ImparcialApi.updateNewsConfig(news);
    return result;
  });

  ipcMain.removeHandler('update-subscribed-projects');
  ipcMain.handle('update-subscribed-projects', async (event, args) => {
    const legislationId = args[0];
    const result = await ImparcialApi.updateSubscribedProjects(legislationId);
    return result;
  });

  ipcMain.removeHandler('get-notifications');
  ipcMain.handle('get-notifications', async (event, args) => {
    const result = await ImparcialApi.getNotifications();
    return result;
  });

  ipcMain.removeHandler('mark-notifications-as-read');
  ipcMain.handle('mark-notifications-as-read', async (event, args) => {
    const notifId = args[0];
    const result = await ImparcialApi.markNotificationAsRead(notifId);
    return result;
  });

  ipcMain.removeHandler('get-pending-scraping-job');
  ipcMain.handle('get-pending-scraping-job', async (event, args) => {
    const jobType = args[0];
    const result = await ImparcialApi.getPendingScrapingJob(jobType);
    return result;
  });

  // ipcMain.removeHandler('');
  // ipcMain.handle('', async (event, args) => {
  
  // });
  
  ipcMain.removeHandler('get-filed-project');
  ipcMain.handle('get-filed-project', async (event, args) => {
    const administrationId = args[0];
    const legislationId = args[1];
    const projectUri = args[2];
    const result = await ImparcialApi.getFiledProject(administrationId, legislationId, projectUri);
    return result;
  });

  ipcMain.removeHandler('get-filed-project-for-recent-legislation');
  ipcMain.handle('get-filed-project-for-recent-legislation', async (event, args) => {
    const administrationId = args[0];
    const legislationId = args[1];
    const projectUri = args[2];
    const result = await ImparcialApi.getFiledProjectForRecentLegislation(administrationId, legislationId, projectUri);
    return result;
  });
  
  // mainWindow.setWindowButtonVisibility(true);

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
  
  // default-src 'none'; connect-src 'self' ws://your-websocket-url.com wss://your-websocket-url.com;
  // 'unsafe-eval' 'unsafe-inline' http://localhost:* ws://localhost:*;
  // 'default-src \'self\'; script-src \'self\' \'unsafe-eval\' http://localhost:3000; script-src-elem \'self\' http://localhost:3000; connect-src \'self\' ws://localhost:3000'

  const isProd = process.env.REACT_APP_ENV == "PROD";
  
  // console.log(process.env.REACT_APP_ENV);
  let policy = "\'unsafe-eval\' \'unsafe-inline\' http://localhost:* ws://localhost:* https://* wss://*";
  if(isProd) {
    policy = "";
  }


  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    callback({
      responseHeaders: {
        ...details.responseHeaders,
        'Content-Security-Policy': [`default-src \'self\' ${policy};`]
      }
    })
  });

};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

app.on('before-quit', () => {

});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
